### ISSUE TITLE
hyperopt dependency is mandatory?

### ISSUE THREAD

**Issue by microprediction** [facebookresearch/nevergrad#1194]
## Steps to reproduce

  1. run nevergrad ngopt without hyperopt installed

## Observed Results

Triggers error when HyperOpt not found in line 2455 of optimizerlib 
  
@registry.register
class NGOpt13(NGOpt12):  # Also known as NGOpt12H
    def _select_optimizer_cls(self) -> base.OptCls:
        if (
            not self.has_noise
            and self.budget is not None
            and self.num_workers * 3 < self.budget
            and self.dimension < 8
            and self.budget < 80
        ):
            return HyperOpt
        else:
            return super()._select_optimizer_cls()

So I suppose the question is, if hyperopt is a dependency then should it be in the requirements?

**Comment by jrapin** [comment]
Hi,
It's a bit complicated for us internally to add default dependencies, so I was avoiding it so far. The integration with hyperopt lacks some robustness as well for now. @teytaud was planning on removing NGOpt dependency to hyperopt, but not sure if this is still planned.
So for now, I'm still unsure what's the best approach :s

**Comment by teytaud** [comment]
NGOpt14 has no dependency on HyperOpt.
NGOpt15 and NGOpt16 (https://github.com/facebookresearch/nevergrad/pull/1238, not yet merged) also do not depend on HyperOpt.
For discrete vars I think NGOpt14 was not very good --- hopefully this is fixed in NGOpt15 (better than NGOpt14 for some discrete vars) and NGOpt16 (better when optimum on the boundary).

**Comment by teytaud** [comment]
Presumably this is solved.
