### ISSUE TITLE
How can I use benchmarking functions to generate data?

### ISSUE THREAD

**Issue by BobYa1** [facebookresearch/nevergrad#1242]
## Steps to reproduce

  1. _How can I use benchmarking functions to generate data?____
  2. _____
  3. _____

## Observed Results

  *How can I use benchmarking functions to generate data?

## Expected Results

  * How can I use benchmarking functions to generate data?

## Relevant Code
How can I use benchmarking functions to generate data?
  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by teytaud** [comment]
Hello! in the dashboard https://dl.fbaipublicfiles.com/nevergrad/allxps/list.html you can find a lot of data (all CSV files)
and you can regenerate data with commands as in 
https://facebookresearch.github.io/nevergrad/benchmarks.html

e.g. 
python -m nevergrad.benchmark noise --seed=12 --repetitions=10 --num_workers=10 --plot

for the "noise" benchmark with 10 cores.

**Comment by BobYa1** [comment]
Hello

Thank you for the fast response. I need list of functions in nevergrad, 24 functions in BBOB. Where can I find it? I am looking for python nevergrad function which gets input vector, math function types and generates their outputs F(x). Where can I find it? The command listed by you is less appropriate for my needs.

Thanks

**Comment by teytaud** [comment]
If you want exactly the functions in BBOB, you might use BBOB directly ? 
In Nevergrad we have YABBOB and many others.

We have many, many benchmarks in Nevergrad, probably the biggest benchmarking suites currently available with a single API. But for BBOB we have our own counterpart, which is similar to BBOB but not exactly equal.

Note that the random translations are a key component of BBOB or YABBOB --- you should not use the functions without translating them, or you will get buggy unreproducible results because the best optimization method will be "print (0,0,0,0,0)" if you do not translate the optimum from 0.

So I do not encourage you to use directly the functions in Nevergrad or in BBOB without the translations as this would lose the entire point of these frameworks. That said, if you want to do it for some reason, you can completely use e.g. https://github.com/facebookresearch/nevergrad/blob/edac4eaa65db5e5e01dc0f1ebcc5134c47b78060/nevergrad/functions/functionlib.py#L86
