### ISSUE TITLE
Ensuring uniformity in told points

### ISSUE THREAD

**Issue by Game4Move78** [facebookresearch/nevergrad#1452]
Do the one shot nevergrad.optimizers.SamplingSearch methods provide more evenly distributed, low-discrepancy sequences in the points given by the ask interface or those provided to the tell interface? In the latter case regions of low density in the told points would be asked repeatedly until feedback is provided with a tell.

I was hoping to have some kind of uniformity in the told points even if they need to be asked many times before feedback is given to the optimiser by a tell.

**Comment by bottler** [comment]
The ask and tell functions together form one interface, they are not alternatives to each other. Points are given by `ask` and the user reports them (with the corresponding function values) with `tell`. For the one-shot methods, `tell` is not very important, because the user could just remember the best points for themselves. No feedback is required. The low discrepancy sequences are provided by ask.

**Comment by Game4Move78** [comment]
Thanks for your help.
