### ISSUE TITLE
Testing the performance of an optimizer on different functions

### ISSUE THREAD

**Issue by lazyoracle** [facebookresearch/nevergrad#171]
When trying to test the results of running the same optimizer on different functions, how do we ensure consistency of representation? By consistency I mean since different function output values in different ranges, does nevergrad involve some normalisation step where all of these values are scaled to a `[0, 1]` range so that it is easier to visualise how far the optimizer reached with a particular function and budget? Is there any suggested method to do this otherwise?

**Comment by jrapin** [comment]
For now there is no consistency between the different functions, and in some cases we may not even know what the minimum is so I doubt we can normalize it :s 

Also, the plotting tool currently assumes the functions are positive since it uses a log-scale. This assumptions should be removed eventually, but we have not found any nice way to handle all cases easily.

In any case, suggestions are welcome ;)

**Comment by jrapin** [comment]
Closing, please reopen if you have more questions ;)
