### ISSUE TITLE
"ValueError: Range cannot be empty (low >= high) unless no samples are taken" with PortfolioDiscreteOnePlusOne

### ISSUE THREAD

**Issue by robert1826** [facebookresearch/nevergrad#183]
## Steps to reproduce

  1. install nevergrad v0.2.0
  2. run the below code

## Observed Results

  ValueError: Range cannot be empty (low >= high) unless no samples are taken

## Expected Results

 there should be no errors running the optimization

## Relevant Code

  ```
  import math
import matplotlib.pyplot as plt
import numpy as np
from nevergrad.optimization import optimizerlib
import nevergrad.instrumentation as instru

np.random.seed(123)

# from: https://www.sfu.ca/~ssurjano/michal.html
def f(x, dim=1, m=10):
    if isinstance(x, float):
        x = [x]

    res = 0
    for i in range(dim):
        res += math.sin(x[i]) * math.sin((i+1) * x[i] * x[i] / math.pi)**(2*m)
    return -res

x = np.linspace(-10, 10, 10**4)
y = [f(i) for i in x]
plt.plot(x, y)

x = instru.var.Array(1).asfloat().bounded(-10, 10, transform="arctan")
my_instrument = instru.Instrumentation(x)

optimizer = optimizerlib.PortfolioDiscreteOnePlusOne(instrumentation=my_instrument, budget=70, num_workers=1)
recomendation = optimizer.optimize(f)

for i in optimizer.archive.items_as_array():
    cur_candidate = optimizer.create_candidate.from_data(i[0])
    func_eval = i[1].mean

    plt.plot(cur_candidate.args[0], func_eval, 'bo')
    print(cur_candidate, func_eval)

plt.show()

  ```

**Comment by jrapin** [comment]
Hi,
Thanks for pointing out. This bug from the mutation which was not designed for 1-dimension space, it will be updated when we decide on the best mutation for this case.

On a side note, we usually consider that using these optimizers instead of a random search becomes really interesting when the dimensionality becomes large enough (10 or mire), so you probably won't get a boost with any algorithm on this use case.

**Comment by jrapin** [comment]
This should now be solved, please reopen this task or another if you still encounter any issue ;)
