### ISSUE TITLE
callback function in the minimize function 

### ISSUE THREAD

**Issue by JiahaoYao** [facebookresearch/nevergrad#268]
Hi, 

For the `minimize` function, there is no argument for the `callback`, even if in the comment I can find https://github.com/facebookresearch/nevergrad/blob/master/nevergrad/optimization/base.py#L467-L468. Thus, I got the error of `TypeError: minimize() got an unexpected keyword argument 'callback'`. Could one tell me how to add `callback` function to the `minimize` function?

**Comment by jrapin** [comment]
Thanks for pointing out. The current way of registering a callback is through this method:
https://github.com/facebookresearch/nevergrad/blob/6905eef00d3db654c0ee35643d250e7ace960865/nevergrad/optimization/base.py#L272-L284

However, it's still undocumented because I am not very happy with the API for now (which means it will probably evolve), and I am a bit afraid of corner cases I didn't think about although I have make use of it without any problem for now. If you have better ideas for this API let me know ;)

**Comment by JiahaoYao** [comment]
Cool. Thanks!
