### ISSUE TITLE
Install via conda

### ISSUE THREAD

**Issue by ytsaig** [facebookresearch/nevergrad#272]
Hi,

Are there plans to support installation via conda, by creating a conda-forge recipe so that `conda install nevergrad -c conda-forge` will work?

**Comment by jrapin** [comment]
Sorry for the delay in answering, I have been busy on other issues.

As far as I understand I would have to track down dependencies to provide a conda recipe. For the "main" install this means mostly BayesianOptimization, which is OK, and CMA-ES, which seems to have been created but has not been maintained for a year and a half. And I have not looked for other the "benchmark" install dependencies :s
Given the that there is no internal use for it on our side, this has lower priority than other issues I must deal with until more people need it, sorry :(

I would keep the issue open so that anyone needing this as well can let us know, or anyone wanting to take this in charge can do it as well ;)

**Comment by HenryDayHall** [comment]
Hey, sorry for the thread necromancy but I'm also looking to install with conda - is this what is needed; https://github.com/conda-forge/nevergrad-feedstock ?

**Comment by jrapin** [comment]
> Hey, sorry for the thread necromancy but I'm also looking to install with conda - is this what is needed; https://github.com/conda-forge/nevergrad-feedstock ?

It's not necromancy, it was not dead yet ;)
That does seem like [it](https://anaconda.org/conda-forge/nevergrad), and that would be great news ;)
@oblute thanks for the work, and let me know if you run into an issue (while I did not want to invest time directly in it, I'm happy to help if something is wrong)

**Comment by oblute** [comment]
@HenryDayHall @jrapin yes, that is what is needed :) you can install with conda now. there should be no issues.
