### ISSUE TITLE
different bounds for variables in an Array

### ISSUE THREAD

**Issue by ldv1** [facebookresearch/nevergrad#287]
Hi,

How to specify different bounds for variables in an Array ?
Consider the following:

```
import nevergrad as ng
from nevergrad import instrumentation as inst
import numpy as np

def square(x):
    return (x[0] - .5)**2 + (x[1] - .5)**2

instrument = inst.Instrumentation( inst.var.Array(2).bounded(-0.5,1.5) )
optimizer = ng.optimizers.OnePlusOne(instrumentation=instrument, budget=100)
recommendation = optimizer.optimize(square)
print(recommendation)
```

The bounds (-0.5, 1.5) are common to all variables; I would like to specify the bounds for each variable without changing the signature of the function to optimize; is it possible?
Thanks for your support!

**Comment by jiangwei221** [comment]
maybe you can split the variable into two diffrent variables with different bounds?
for example:
```
ng.Instrumentation(ng.var.Array(1).bounded(-1, 1), ng.var.Array(1).bounded(-0.05, 0.05))
```

**Comment by ldv1** [comment]
That was my first attempt, and I got:

`TypeError: square() takes 1 positional argument but 2 were given`

so, it is possible, but I should modify the signature of the function to minimize. That's what I want to avoid.

**Comment by jrapin** [comment]
A simple option would be to use some kind of overlay/decorator like this one:
```python
def concat(func)
    def new_func(*args):
        return func(np.concatenate(args, axis=0))
    return new_func
```
Then you'd do `recommendation = optimizer.minimize(concat(square))` (btw note that `optimize` is disappearing in newer versions, in favor of `minimize` which is more precise and is less likely to cause errors)
Would that be cheating ? :D 

If that can help, I think making 
```python
ng.Instrumentation(ng.var.Array(2).bounded([-1, -0.05], [1, -0.05])
```
should only require minor adjustments in the code, I could do it in little time.

Also, I am currently working on more advanced instrumentations which could (hopefully) help in having more flexibility in creating custom variables, but I would not count on it in the short term.

A last option would be to create your own Variable, giving you a lot of freedom. However this is more advanced, not very documented, and since this part of code is currently undergoing very heavy changes, it may not stay compatible for long :s

**Comment by jrapin** [comment]
Would #289 work for you? This allows the syntax mentioned above:
```python
ng.Instrumentation(ng.var.Array(2).bounded([-1, -0.05], [1, 0.05])
```

**Comment by ldv1** [comment]
yes, it would be great ! (though I haven't tested it)
it would be even better if it would stick to the widerspread convention (see e.g. scipy.optimize.minimize) bounds is a sequence of (min,max) pairs.

**Comment by jrapin** [comment]
When dealing with huge multidimensional arrays, having an array of min, max to specify the bounds would be pretty much a mess and inefficient :s 
I would rather keep it that way, at least for now, sorry

**Comment by jrapin** [comment]
The PR is now merged, let me know if you have any issue with it. Closing this for now but don't hesitate to reopen ;)

**Comment by ldv1** [comment]
It works like a charm; big thanks for your prompt support!
