### ISSUE TITLE
PSO has unusually high population std

### ISSUE THREAD

**Issue by arturomf94** [facebookresearch/nevergrad#296]
Consider the following code: 

```
import nevergrad as ng
import numpy as np
def square(x, y=12):
    return sum((x - .5)**2) + abs(y)
popsize = 100
episodes = 500
budget = popsize * episodes
op = ng.optimizers.registry['PSO'](
      instrumentation = 200,
      num_workers = popsize,
      budget = budget)
for ep in range(budget // popsize):
  solutions = []
  candidates = []
  for i in range(popsize):
    candidate = op.ask()
    candidates.append(candidate)
    solutions.append(candidate.args[0])
  solutions = np.asarray(solutions)
  candidates = np.asarray(candidates)
  fitness = []
  for i in range(popsize):
    value = square(solutions[i])
    fitness.append(value)
    op.tell(candidates[i], value)
  if ep % 10 == 0:
    print(np.std(solutions))
recommendation = op.provide_recommendation()
```
The standard deviation of the population here is unusually high. For other optimizers (e.g. DE, TBPSA, etc) the std seems normal. Is this behaviour expected?

**Comment by jrapin** [comment]
Thanks for raising the issue, I'm not sure if it's a bug or a feature :D

@teytaud this come from the initialization:
https://github.com/facebookresearch/nevergrad/blob/306df3810d2bca688ab18f5bf996de256a0fee42/nevergrad/optimization/optimizerlib.py#L601-L604
`PSO` is implemented on `[0, 1]` and the points are transformed to `R` when needed, hence since the initialization is uniform on `[0, 1]`, they span all R and are definitely not Gaussian. This is due to me changing the transform some time ago, I did not consider this effect.

Options:
 1. sample with a Gaussian and transform to `[0, 1]` (for both position and speed?)
 2. can it work on `R` natively?

**Comment by arturomf94** [comment]
Looking at other implementations (e.g. [pyswarms](https://github.com/ljvmiranda921/pyswarms)), I reckon it might be better to initialize with something of the following flavour: `np.random.uniform(-1, 1, dimension)`. This might be scaled up or down with another parameter: `sigma * np.random.uniform(-1, 1, dimension)`. Considering that PSO usually has premature convergence it might be useful to be using a uniform distribution rather than a gaussian one. 

My guess is that the results of robustness on deceptive functions will still hold.
