### ISSUE TITLE
Add a list of optimization algorithms to the doc

### ISSUE THREAD

**Issue by LaurentMazare** [facebookresearch/nevergrad#58]
Thanks for all the hard work on nevergrad, it's very useful.

It would be nice to have some documentation on the currently supported optimizers. The comments in [optimizerlib](https://github.com/facebookresearch/nevergrad/blob/master/nevergrad/optimization/optimizerlib.py) already contain some details - maybe would it be possible to automatically generate some documentation out of it (using some tools from [this list](https://wiki.python.org/moin/DocumentationTools) ?).

Ideally some documentation could also be added to the optimizers from [recastlib](https://github.com/facebookresearch/nevergrad/blob/master/nevergrad/optimization/recastlib.py).

**Comment by jrapin** [comment]
Hi Laurent,
Thank you for your message ;)
I fully agree that a list would be welcome. For now it is possible to get it with
```
from nevergrad.optimization import registry
list(registry)
```

Would it be helpful for a start to have either or both:
- this command explicitly written in the README
- a file where this list is dumped automatically
+ add a line stating some default best choices.

In the long term documentation tools will probably be helpful, but for now since the optimizer docstrings are a bit lacking... it would not give more information than just the list :s

**Comment by LaurentMazare** [comment]
`list(registry)` is pretty neat, I didn't know about it. Having it on the README would be nice.
As for having a dump of the list, I would not care that much about it as I already have nevergrad installed but maybe would it be useful for potential new users so that they can check the optimizer list before installing the library.

Longer term documentation would certainly be helpful too depending how the library evolves.

**Comment by LaurentMazare** [comment]
Thanks Jeremy, that's very useful for users that are a bit away from the field like me so thatwe learn about the pros and cons of each method.
