### ISSUE TITLE
No 'explore' method in BayesianOptimization class

### ISSUE THREAD

**Issue by HawkTom** [facebookresearch/nevergrad#70]
In the class of  "class BO(recaster.SequentialRecastOptimizer)", in <recastlib.py>.  The framwork operates the code " bo.explore(points_dict)". But there is no explore function in BayesionOptimization class. 

The code I use to test BO classs is:
```python
from nevergrad.optimization import recastlib

def square(x):
    return sum((x - .5)**2)

bboo = recastlib.BO(dimension=2, budget=10, num_workers=1)
bboo.qr = "lhs"
bboo._optimization_function(square)
```
The error raised in the terminal is :
```python
    bo.explore(points_dict)
AttributeError: 'BayesianOptimization' object has no attribute 'explore'
```

**Comment by jrapin** [comment]
Thanks for notifying this. The API of the bayesian-optimization package has indeed changed. I have set the requirement to version 0.6.0 (old one) for now as a quickfix.

A few remarks on the code:
instead of setting `qr="lhs"`, you could have `instanciated recastlib.LBO` instead. `qr` should probably be set to private.
I would strongly discourage using the `_optimization_function` private method of the recast algorithms. They are the only ones having this method, and it's mostly a hack to be able to provide an ask and tell interface for algorithms implemented in external packages without this interface.
Seems like the new version of the bayesian-optimization package supports ask and tell by the way, so hopefully we will have time to reimplement the nevergrad overlay, and `_optimization_function` may just disappear.

I am closing this, and opening an new issue for upgrading to bayesian-optimization 1.0.0 (we probably won't have time internally to deal with this before a couple of weeks though :( )
