### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by afshawnlotfi** [facebookresearch/nevergrad#794]
Does this package have GPU support. If so is there anywhere I can find more information. My optimization takes a long time and I was wondering if I could take some of the load off as I have plenty of graphics cards lying around.

**Comment by jrapin** [comment]
Hi,
Short answer is no, initially this package was mostly designed for functions that take a lot of time to evaluate, so not with efficiency at its core (optimizer's computation time is then negligeable). On the longer time, it may be built in for some cases eventually, but I doubt that will happen before a few years.

That being said, can you state a bit more on your settings? I might be able to identify pain points.
- how long does your function take to evaluate?
- what is your parametrization?
- what optimizer(s) do you use?

**Comment by afshawnlotfi** [comment]
I think I just gave the minimize function too many parameters and it was just a never-ending run. However if you are interested here it is:

```
optimizer = ng.optimizers.NGO(parametrization=parametrization, budget=100, num_workers=4)
parametrization = ng.p.Instrumentation(
    blades=ng.p.Scalar(lower=1, upper=12).set_integer_casting(),
    pitch=ng.p.Scalar(lower=0.1, upper=2.0),
    hub_diameter=ng.p.Log(lower=1.0, upper=10.0),
    diameter=ng.p.Log(lower=1.0, upper=10.0)
)
with futures.ThreadPoolExecutor(max_workers=optimizer.num_workers) as executor:
   recommendation = optimizer.minimize(negThrust,  executor=executor, batch_mode=False)
   print(recommendation.value)
```

I was trying to optimize thrust for a propeller for a cool little experiment. If I gave it more than 2 parameters it would run forever. Idk maybe one of those state-explosion problems.

**Comment by jrapin** [comment]
That shouln't take so long if your function is fast.
From what you are saying this is in dimension 4. It may become slow at dimension >>1000, and then again mostly when using `Choice` parameters.
The underlying optimizer used by `NGO` in your settings is `DoubleFastGADiscreteOnePlusOne`, which does not do anything requiring slow computation.

Then if it's slow it should come from the function side:
- maybe it tries to evaluate the function at points where it is too difficult to compute?
- I would be cautious with the use of `ThreadPoolExecutor` since in Python it may not bring any speed up. Also since you mentioned using GPU, maybe your function does not parallelize well, leading to a deadlock?

I'd recommend these debugging steps:
- add verbosity=2 to `minimize`, that will print out what happens
- removing the executor so that the optimization happens sequentially
- for further debugging, you can use the `ask` and `tell interface of optimizer directly
