### ISSUE TITLE
Continuous constraints

### ISSUE THREAD

**Issue by teytaud** [facebookresearch/nevergrad#801]
I start coding something for constraints.
I want to deal separately with constraints which are not just boolean: constraints of the form g(x) >=0.

Not sure if I should
(a) modify cheap constraints so that _constraints_checkers is a list of mapping to Union(bool, float).
(b) or add a second list e.g. _continuous_constraints_checkers which is a list of mapping to float.
(c) like b, but in addition we add a boolean constraint for each continuous constraint, so that algorithms only dealing with boolean constraints don't have to worry about continuous constraints.

I would go for (c), unless someone tells me this is not the right pythonic way of dealing with that :-)

**Comment by jrapin** [comment]
Is that in a hurry? I have plans to update the constraint management so I would rather not add more features just now.
However I'd need to understand the needs.

What is the aim here? you want the float as a source of information? How would you use it? because the way it is done, `internal_ask` is not supposed to access this information, it's only dealt with at the base optimizer level.

And as a choice I would tend to go for (a) which requires minimal changes, although that can lead to weird silent errors if people were sending floats instead of booleans.

**Comment by teytaud** [comment]
Yes I want the float as a source of information.
I would use it for implementing many other methods for constraint management.
The simplest tool is penalization, with multiplicative factor growing from zero to +infinity as num_ask grows from 0 to budget.
Ok for (a) then.

**Comment by teytaud** [comment]
in progress https://github.com/facebookresearch/nevergrad/pull/807/files

**Comment by teytaud** [comment]
Done.
