### ISSUE TITLE
check which of the applied cheap_constraint constraints are met or not?

### ISSUE THREAD

**Issue by TokyAxel** [facebookresearch/nevergrad#817]
Hello, I have been using Nevergrad for a month so I want to know how to check which of the applied cheap_constraints are met or not?

I have already found this function "satisfies_constraints()" but it always returns False even if the constraints on x [0] and x [1] seem to be satisfied. Maybe I don't know how to use it, if this is true where can I find an example of use? Here is the way i test it 

  ```
optimizer = ng.optimizers.OnePlusOne(parametrization=2, budget=100)
optimizer.parametrization.register_cheap_constraint(lambda x: x[1] > 1)
optimizer.parametrization.register_cheap_constraint(lambda x: x[0] > 0)
recommendation = optimizer.minimize(func) 
print(optimizer.parametrization.satisfies_constraints())
  ```

**Comment by jrapin** [comment]
Hi,
Sorry for the delay, I have been away from the project for some time.
The problem here is that you are checking that the *initial* parametrization satisfies the constraint. By default, given your inputs, it does not because it is `[0, 0]`.
However, you could try `recommendation.satisfies_constraints()` which (hopefully) should return `True`
There is no way to actually check which one is not satisfied, mostly because it is not useful for the inner workings of the optimizers, and because I considered it is usually faster to try it yourself in that case,
eg :`recommendation.value[1] > 0`
Why would you need to check which one specifically?
Does that answer your question?

**Comment by TokyAxel** [comment]
Thank you for reply :) 
We need to check which one specifically 'cause the project will handle a tons of constraints so we want to know how many is satisfied.   
And yes we have tried your recommendations and it was really helpful.

**Comment by jrapin** [comment]
Then I would recommend keeping track of the constraints and computing them directly yourself. I would rather avoid adding a specific API for this since it is something one can compute easily oneself (and since we are in the process of changing a lot of stuff regarding constraints so any additional API would be unstable :s)

Also I would recommend waiting for #807 which will be more appropriate for handling large number of constraints, I'm afraid the current method would not be very satisfactory (it will probably just ignore the constraints if it can't satisfy them all at once :s)

**Comment by TokyAxel** [comment]
Your recommendations are noted for the following.
Thanks for mentioning # 807. I'll keep tracking on it.

**Comment by teytaud** [comment]
#807 and other PRs in progress (#934) should improve stuff but for complicated cases we have not yet implemented the state of the art. I hope I can find time for this.

**Comment by TokyAxel** [comment]
Ok, and thanks for recommendation by mentioning #934  :-)

**Comment by teytaud** [comment]
Did you try 934 and did you like it ? We have debates about merging it or not :-)

**Comment by TokyAxel** [comment]
Use an auxiliary optimizer to check if each constraint is satisfied using distance penalization, right? I'm sure it will be really helpful when we want to find the best way to satisfy all the constraints.
