### ISSUE TITLE
Feature Request: NSGA-II Optimizer

### ISSUE THREAD

**Issue by pacowong** [facebookresearch/nevergrad#820]
## Background

NSGA-II is a well known, fast sorting and elite multi-objective genetic algorithm. 

It is in the wishlist: https://github.com/facebookresearch/nevergrad/issues/761

## What to do
Let me be a volunteer. I'll add NSGA-II optimizer following the examples in DE and ES in Nevergrad.

As an alternative, we may consider adding an interface to jMetalPy. When I compare the ES implementation in jMetalPy ([here](https://github.com/jMetal/jMetalPy/blob/master/jmetal/algorithm/singleobjective/evolution_strategy.py)) and Nevergrad ([here](https://github.com/facebookresearch/nevergrad/blob/master/nevergrad/optimization/es.py)), my feeling is that it will be hard to maintain.

**Comment by jrapin** [comment]
Since we are doing research with nevergrad, I tend to prefer when things are implemented internally, and that would be one fewer requirement ;)

If you are up for implementing it I am perfectly fine with it (and I expect @teytaud will be as well ;) ).
Still be careful, the multiobjective support within optimizer class is still a bit hacky and will probably evolve (I don't like that there is now both a `loss` and a `losses` in the `Parameter` class, but don't know how to do something simpler and generic enough for now). The only optimizer which actually use the multiobjective loss is currently `DE` indeed, so that should be the main example.
